config/routes.rb
Rails.application.routes.draw do
get "/" => "homes#top"
get "/homes/help" => "homes#help"
resources :sessions
resources :users
resources :blogs do
collection do
post :confirm
end
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    include CarrierWave::MiniMagick
    belongs_to :user
    mount_uploader :blog_image, BlogImageUploader
    validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: true
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
    def new
        if params[:back]
            @blog = Blog.new(blog_params)
        else
            @blog = Blog.new
        end
    end

    def create
        if params[:back]
            render :new
        else
            Blog.create(blog_image: params[:blog][:blog_image], content: params[:blog][:content], 
            user_id: current_user.id)
            redirect_to new_blog_path
        end
    end

    def index
        @blogs = Blog.all
    end

    def update
        @blog = Blog.find(params[:id])
        if @blog.update(blog_params)
            redirect_to blogs_path, notice: "ブログを編集したで"
         else
            render :edit
        end
    end

    def edit
        @blog = Blog.find(params[:id])
    end

    def destroy
        @blog = Blog.find(params[:id])
        @blog.destroy
        redirect_to blogs_path, notice:"ブログをほかしたで"
    end

    def show
        @blog = Blog.find(params[:id]) 
        #@user = User.find(id:blog.user_id)
    end

    def confirm
        @blog = Blog.new(blog_params)      
    end

    private
    def blog_params
      params.require(:blog).permit(:blog_image, :content, :image_cache, :user_id, :image)                         
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def top
    end
    def help
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end
    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to user_path(@user.id)
          else
            render :new
          end
    end
    def index
    end
    def update
        @user = User.find(params[:id])
    end
    def edit
        @user = User.find(params[:id])
    end
    def destroy
    end
    def show
        @user = User.find(params[:id])
    end

    private
  
    def user_params
        params.require(:user).permit(:name, :email, :password,
                                    :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    def logged_in?
    current_user.present?
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/confirm.html.erb
<div class="main-top">
    <h3>これで、ええのん？</h3>
    <%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
    <%= image_tag(@blog.blog_image.url) if @blog.blog_image && @blog.blog_image.url %>
    <%= form.hidden_field :image_cache %>
    <%= form.hidden_field :content %>
    <p>:<%= @blog.content %></p>
    <%= form.submit "投稿する" %>
    <% end %>
</div>

app/views/blogs/edit.html.erb
<div class="main-top">
    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
<h2>編集したってや</h2>
<%= form_with(model: @blog, local: true) do |form| %>
    <div>
        <%= form.label :画像貼ってな %><br>
        <%= form.file_field :blog_image %>
    </div><br>
    <div>
        <%= form.label :コメントしてな %><br>
        <%= form.text_field :content %>
    </div><br>
    <%= form.submit value="編集するわ" %>
<% end %>
</div>

app/views/blogs/index.html.erb
<div class="main-top">
<h1>投稿見てみよか</h1>
<% @blogs.reverse_each do |blog| %>
    <div class="index-window">
      <% if blog.blog_image? %>
        <p><%= image_tag blog.blog_image.url %></P>
      <% end %>
      <p>:<%= blog.content %></p>
      <p style="color:gray; text-align: right" ><%= blog.updated_at.strftime("%Y-%m-%d %H:%M") %>
      <p style="color:gray; text-align: right"><%= blog.user.name %>が投稿したで</p>
      <div style="text-align: right; margin-right:10px">
        <%= link_to "確認するで", blog_path(blog.id)  %>
        <%= link_to "編集するで", edit_blog_path(blog.id)  %>
        <%= link_to 'ほかすで', blog_path(blog.id), method: :delete, data: { confirm: 'ほかしても、ええのん？' } %>
      </div>
    </div>
<% end %>
</div>

app/views/blogs/new.html.erb
<div class="main-top">
<h2>投稿したってや</h2>
<%= form_with(model: Blog.new, local: true, url: confirm_blogs_path) do |form| %>
    <div>
        <%= form.label :画像貼ってな %><br>
        <%= form.file_field :blog_image %>
    </div><br>
    <div>
        <%= form.label :コメントしてな %><br>
        <%= form.text_field :content %>
    </div><br>
    <%= form.submit value="投稿するで" %>
<% end %>
</div>

app/views/blogs/show.html.erb
<div class="main-top">
  <h1>こんな感じやねん</h1>
    <div class="index-window">
      <% if @blog.blog_image? %>
        <p><%= image_tag @blog.blog_image.url %></P>
      <% end %>
      <h2>:<%= @blog.content %></h2>
      <p style="color:gray; text-align: right" ><%= @blog.updated_at.strftime("%Y-%m-%d %H:%M") %></p>
      <div style="text-align: right; margin-right:10px">
        <%= link_to "編集するで", edit_blog_path(@blog.id)  %>
        <%= link_to 'ほかすで', blog_path(@blog.id),data: { confirm: 'ほかしても、ええのん？' }, method: :delete %>
      </div>
    </div>
  </div>
</div>

app/views/homes/help.html.erb
<div class="main-top">
    <br>
    <h1>HELP!</h1>
    <p>助けて欲しいのは、こっちやねん……。</P>
    <p>I always need your kindly support</p>
    <br>
    </div>

app/views/homes/top.html.erb
<div class="main-top">
    <br>
    <h1>Welcome to Fakelook!</h1>
    <p>……最初の一歩は、いつもここから</P>
    <br>
    <%=link_to "新規登録はこちら", new_user_path %><br><br>
    <%= link_to "ログインはこちら", new_session_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fakelook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
    <div class ="header-logo"><%= link_to("Fakelook","/") %></div>
    <ul class ="header-menus">
      <% if logged_in? %>
        <li><%= current_user.name %></li>
      <% end %>
      <li><%= link_to("投稿するで","/blogs/new") %></li>
      <li><%= link_to("投稿見るで","/blogs") %></li>
      <% if logged_in? %>
        <li><%= link_to "自己紹介", user_path(current_user.id) %></li>
        <li><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>
      <% else %>
        <li><%= link_to "新規登録", new_user_path %></li>
        <li><%= link_to "ログイン", new_session_path %></li>
      <% end %>
      <li><%= link_to("へるぷ","/homes/help") %></li>
    </ul>
  </header>
      <% if flash[:notice] %>
      <div class="flash">
        <br>
        <%= flash[:notice] %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<div class="main-top">
    <% if @user.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
            <ul>
                <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
            </ul>
        </div>
    <% end %>
    <h1>登録したってや</h1>
    <%= form_with(model: @user, local: true) do |f| %>  
        <%= f.label :　　　　　　名前 %>
        <%= f.text_field :name %>
        <br>
        <%= f.label :　　　　　メアド %>
        <%= f.email_field :email %>
        <br>
        <%= f.label :　　　パスワード %>
        <%= f.password_field :password %>
        <br>
        <%= f.label :確認用パスワード %>
        <%= f.password_field :password_confirmation %>
        <br><br>
        <%= f.submit "登録するで" %>
    <% end %>
</div>

app/views/users/show.html.erb
<div class="main-top">
    <h1><%= @user.name %>のページ</h1>
    <p>メールアドレス: <%= @user.email %></p>
</div>